### ISSUE TITLE
Intersecting NanoVar SVs

### ISSUE THREAD

**Issue by asmariyaz23** [cytham/nanovar#10]
Hello,

I have 2 samples (twins) for which I have used NanoVar to successfully call SVs. I want to find out the intersection between these VCFs. I used bedtools' intersectBed to find this intersection but I get the following error:

```
ERROR: Received illegal bin number -1 from getBin call.
Maximum values is: 2396745
This typically means that your coordinates are
negative or too large to represent in the data
structure bedtools uses to find intersections.ERROR: Unable to add record to tree.
```

I was wondering if you ever came across this issue in your work as I saw that NanoVar paper also used the same bedtools intersectBed to find intersection. 

Thank you,
Asma

**Comment by cytham** [comment]
Hi @asmariyaz23,

I'm sorry but I have not encountered that error before while intersecting two of NanoVar's VCF files. More importantly, I wouldn't intersect the VCF files that way as I am not sure how BEDTools-intersect will handle the breakends of each SV. It is safer to extract all the breakend coordinates into a BED file and then use them for intersection. For example, if you have a 1kb deletion from chr1:5000 to chr1:6000, it is better to extract them into a BED file with two entries using a 100 bp size window : 
```
chr1    4950    5050
chr1    5950    6050
````
This will ensure both breakend of the deletion is accounted for. As the VCF file will only explicitly display the first coordinate (chr1:5000) in its second column while the second coordinate (chr1:6000) is hidden in the INFO field, I am not sure BEDTools intersect will take the second coordinate into consideration. 

I have actually released the beta version of my SV analyzing tool, VariantBreak (https://github.com/cytham/variantbreak), which takes multiple NanoVar VCF files and integrate them into a single data CSV table. You can also input your own annotation GTF file or other filtering BED files to annotate or add a filter label to each SV recorded in the table. The tool is new and I have not released the documentation yet, so please ask your questions here if you have any. Anyhow, please also note that the output of VariantBreak can be visualized in a heatmap called VariantMap which will be released soon, in case you are confused while reading the README. 

Best,
cy
