### ISSUE TITLE
Annotating variants called by NanoVar

### ISSUE THREAD

**Issue by asmariyaz23** [cytham/nanovar#2]
Hello Cy,

Could you comment on how you go about annotating the VCF file generated by NanoVar. I have tried AnnoVar and AnnotSV, all but the Exac scores could be achieved from them. Have you done any work on getting annotations for Exac on the variants called by your software?

Thank you,
Asma

**Comment by cytham** [comment]
Hi Asma,

Thanks for writing in.

I am still working on a separate tool to annotate SVs, so I can't comment much on it right now. You can try to overlap the SVs in the VCF file with GFF files for gene annotation, or ChIP-seq results for binding site annotation. I am not sure what is Exac, do you mean the "exome aggregation consortium"? If yes, I don't have much experience with it and I can't access their website as they have shifted to gnomAD. Anyway, I am also not sure if the consortium has annotations for structural variants, as i suppose it is mostly SNPs.

Best,
cy
