### ISSUE TITLE
sv_cluster() Error

### ISSUE THREAD

**Issue by kztyes** [cytham/nanovar#22]
TypeError: sv_cluster() missing 1 required positional argument: 'seed'
The following picture is my detailed output:

![微信图片_20210428102638](https://user-images.githubusercontent.com/55338332/116337133-3f4cbe00-a80c-11eb-8204-c75e61d65212.png)

**Comment by cytham** [comment]
Hi @kztyes, may I know what version of NanoVar you are using? Can you please try out the newest version 1.3.9?

**Comment by kztyes** [comment]
Hello, @cytham, after the version 1.3.9 has been replaced, new problem arises:
![Uploading 微信图片_20210428170255.png…]()

**Comment by cytham** [comment]
Hi @kztyes the error means that the contig "1" found in your BAM file is not found in the reference genome. Please ensure that the reference genome you provide is the same one you used for read mapping.

**Comment by kztyes** [comment]
Hi @cytham , I think I probably know why this problem occurs. My BAM file is divided into chromosomes , I used the BAM file of chromosome 2 to detect structural variation through nanovar, so there is no contig "1". What should I do in this situation？

**Comment by cytham** [comment]
Can I check if the chromosome header in the BAM file matches the chromosome of the alignments? For example, does the chromosome 2 BAM file only state chromosome 2 in its header, etc. 

And do you also split the reference to individual chromosomes?

**Comment by kztyes** [comment]
I didn't split the reference to individual chromosomes , and this is my header file: 
[hg002_allreads_ngmlr.2.txt](https://github.com/cytham/nanovar/files/6395936/hg002_allreads_ngmlr.2.txt)

**Comment by cytham** [comment]
can you index the reference genome FASTA file using `samtools faidx` and send me the .fai file? Thanks

**Comment by kztyes** [comment]
发自我的华为手机

**Comment by cytham** [comment]
Hi @kztyes, I am having a problem understanding the message.

**Comment by kztyes** [comment]
After commenting out the following code, Nanovar works well. Then it outputs two VCF files, which one should I use, Pass or Total ?

`   # Check BAM contigs in reference genome
    # if input_type == 'bam':
    #     for c in contig_list:
    #         if c not in contig_len_dict:
    #             logging.critical("Error: Contig %s in BAM is absent in reference genome" % c)
    #             raise Exception("Error: Contig %s in BAM is absent in reference genome" % c)`

**Comment by cytham** [comment]
@kztyes Yea it worked because you just removed the function to ensure that there are same contig labels in both the reference genome and BAM file. The reason you got that error in the first place is because you had mismatching contig names between your reference genome and BAM file. Please proceed at your own risk to comment this section out. I recommend to check the contig labeling of your reference file (e.g. whether chromosome 1 is labeled "1" or "chr1" or something else)

You should use the Pass VCF as it has been enriched for more true variants.

**Comment by cytham** [comment]
@kztyes any updates on this issue? if not I will close it for now.
