### ISSUE TITLE
Why sv_support_read contains reads from other chromosome?

### ISSUE THREAD

**Issue by yekaizhou** [cytham/nanovar#24]
Hi,

I am using sv support reads for downstream analysis. I found that the reads responsible to detect one particular SV often come  from different chromosomes, even for INS and DEL. Is it the internal algorithm set up? As other SV detection algorithms only cluster SVs from the nearby reads within the same chromosome.

**Comment by cytham** [comment]
Hi @yekaizhou, what version of NanoVar are you using? 

By right, the reads that support each SV should only be overlapping with the breakpoints of the SV. So in the case of inter-chromosomal translocations, the supporting reads will align to different chromosomes. However, for INS or DEL, the supporting reads should be only aligning to the SV region of the same chromosome. Can you show me some examples of your observation?

**Comment by cytham** [comment]
@yekaizhou Are you still having this problem?

**Comment by yekaizhou** [comment]
> @yekaizhou Are you still having this problem?

Hi I discovered that it was the problem of the downloaded data. Sorry that I did not reply earlier.

Thanks anyway! NanoVar is really nice at discoverying novel SVs at low sequencing depth.
