### ISSUE TITLE
CRITICAL - Error: hs-blastn alignment failed

### ISSUE THREAD

**Issue by MingchenInSZ** [cytham/nanovar#29]
This error always occurred, when i calling sv using mapped BAM(minimap2), and i do not really know what has happed. what should i do to locate the error?
`nanovar   -f hg38 -t 20 --force /home/user/.../alignment/20200914_1356_6F_PAF26223_da14221a/readset1.bam /home/user/.../GRCh38_full_analysis_set_plus_decoy_hla.fa   /home/user/.../variants/nanovar/20200914_1356_6F_PAF26223_da14221a`

[NanoVar-170721-1249.log](https://github.com/cytham/nanovar/files/6834367/NanoVar-170721-1249.log)

**Comment by cytham** [comment]
@MingchenInSZ I realized many of your contigs contain the '-' symbol. Can you find a way to remove it from each contig name and try running again?

Sorry for the inconvenience.

**Comment by MingchenInSZ** [comment]
@cytham  Thanks a lot. I've tried as your suggestions, replacing all '-'  into '_'  in reference. Then I run again, but the same error occurred.
As the log printed, hs-blastn index and alignment all failed, and i found the temp1.fa worked without exition and while 
[NanoVar-220721-0304.log](https://github.com/cytham/nanovar/files/6860845/NanoVar-220721-0304.log)
processing temp2.fa  the error occurred.

**Comment by cytham** [comment]
Sorry can you also try to remove any ":" or "~" symbols too? Also, if possible, can you try with the latest version of NanoVar (v1.3.9). Thanks

**Comment by MingchenInSZ** [comment]
@cytham  Thank you for your patience， I removed all records contained ":" or "-", and removed all the HLA sequeueces which might contain uncommon signs. And i upgrade the nanovar to 1.3.9. This run, the warning disappeared, but the same error  occurred。
hs-blastn index and alignment always failed, the installation and configuration of hs-blastn need any special attentions?
[NanoVar-260721-1702.log](https://github.com/cytham/nanovar/files/6881905/NanoVar-260721-1702.log)

**Comment by cytham** [comment]
@MingchenInSZ Sorry for the delayed response.

May I know how you've installed NanoVar? Did you install hs-blastn independently by yourself?

**Comment by MingchenInSZ** [comment]
@cytham Awesome thanks.  Firtly, I‘ve installed NanoVar version 1.3.6 by running pip install command, and upgraded to 1.3.9 as your suggestion in former response. And hs-blastn was installed independently, and no errors or warnings occurred during installtion.

**Comment by cytham** [comment]
@MingchenInSZ May I know how did you install hs-blastn? and which version did you install?

**Comment by MingchenInSZ** [comment]
@cytham Thanks for your prompt reply.
I cloned "query" package from github, and run make command to intall local.
`
git clone https://github.com/chenying2016/queries.git
cd queries/hs-blastn-src/
make
`
and the version is 2.0.0
![123](https://user-images.githubusercontent.com/7196243/127818535-894c0dd9-6773-4c81-a993-edbc384c3173.png)

**Comment by cytham** [comment]
@MingchenInSZ NanoVar can only utilize version 0.0.5 of hs-blastn. So this might be the problem. Please refer to the NanoVar's README for instructions on installing the version 0.0.5 of hs-blastn, or you can just refer to here:
```
# Download and compile the 0.0.5 version
git clone https://github.com/chenying2016/queries.git
cd queries/hs-blastn-src/v0.0.5
make

# Copy hs-blastn binary to path (e.g. ~/bin)
cp hs-blastn ~/bin
```

**Comment by MingchenInSZ** [comment]
@cytham Awesome thanks! I've tried as suggestions and run successfully.
