### ISSUE TITLE
After run nanovar, we cannot get the vcf results, could you give some advice?

### ISSUE THREAD

**Issue by zch0803** [cytham/nanovar#38]
We use command `nanovar -t 24 ourbam.bam hg38.fna ourdir` to run nanovar. After calculating, we cannot find output vcf in outdir. Here is the output file:

> fig    GCA_000001405.15_GRCh38_no_alt_analysis_set.counts.obinary  NanoVar-251021-1535.log GCA_000001405.15_GRCh38_no_alt_analysis_set.counts  genome.sizes

And in the logfile, we cannot find anything wrong, the last log is 

> "[25/10/2021 20:03:44] - INFO - Re-clustering INS/INV SVs and merging
[25/10/2021 20:05:18] - INFO - Neural network inference
[25/10/2021 20:05:45] - DEBUG - Creating converter from 3 to 5".

So, we would be very grateful for your help , could you give some advice?

**Comment by cytham** [comment]
@zch0803 Hi, so were you able to obtain the VCF output files?

**Comment by zch0803** [comment]
Yes, There are two ways to solve the problem. The first way is to modify the "YourPath/miniconda3/envs/sv/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py" file. The second way by updating the nanovar to v1.4.1 is also ok. And the results are no difference.

**Comment by cytham** [comment]
Thanks @zch0803. Glad that the problem has been resolved.
