### ISSUE TITLE
Run fails at nv_cluster.py IndexError: list index out of range

### ISSUE THREAD

**Issue by asmariyaz23** [cytham/nanovar#4]
Hello Cytham,

I successfully ran 2 of my samples with NanoVar. But I get the following error with the next 2 samples. Could you shed some light on the error below?

Thank you,
Asma

```
Running: nanovar -t 24 /scratch/autism_minion/Structural_variant_analysis/FAM1_MU004/trimmed_reads/trimmed.fastq /scratch/RESOURCES/hg38/hg38.fa /scratch/autism_minion/Structural_variant_analysis/FAM1_MU004/nanovar
[23/01/2020 02:59:10] - NanoVar started
Mapping reads and calling SVs - -Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.6/bin/nanovar", line 188, in <module>
    main()
  File "/root/.pyenv/versions/3.6.6/bin/nanovar", line 174, in main
    run.cluster_nn()
  File "/scratch/SOFTWARE/nanovar/nanovar/nv_characterize.py", line 116, in cluster_nn
    cluster_out = sv_cluster(self.total_subdata, self.total_out, self.buff, self.maxovl)
  File "/scratch/SOFTWARE/nanovar/nanovar/nv_cluster.py", line 39, in sv_cluster
    connectdict, classdict = intersection(intersect, bed1)
  File "/scratch/SOFTWARE/nanovar/nanovar/nv_cluster.py", line 194, in intersection
    if i.split('\t')[4] in svgroup(i.split('\t')[9]):
IndexError: list index out of range
Mapping reads and calling SVs - \Traceback (most recent call last):
  File "/scratch/autism_minion/Long-reads/minion_pipeline.py", line 442, in <module>
    MinIonPipeline().run()
  File "/scratch/autism_minion/Long-reads/minion_pipeline.py", line 282, in run
    pipeliner.run()
  File "/scratch/autism_minion/Long-reads/PyLib/Pipeliner.py", line 53, in run
    run_cmd(cmd.get_cmd())
  File "/scratch/autism_minion/Long-reads/PyLib/Pipeliner.py", line 17, in run_cmd
    subprocess.check_call(cmd, shell=True)
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nanovar -t 24 /scratch/autism_minion/Structural_variant_analysis/FAM1_MU004/trimmed_reads/trimmed.fastq /scratch/RESOURCES/hg38/hg38.fa /scratch/autism_minion/Structural_variant_analysis/FAM1_MU004/nanovar' returned non-zero exit status 1.
```

**Comment by cytham** [comment]
Hi Asma,

Sorry for the late reply.

It is possible that something is different in this FASTQ file compared to the others which had the successful run (e.g. special symbols in read names/reference contig names). Can you show me the read names of the reads or perhaps send me a small FASTQ for a test run?

Anyway, I am releasing v1.2.8 in the next few days. It is faster and more precise than the previous versions. It may also resolve your issue. I would strongly recommend you re-running your samples on the new version as soon as its out.

Thanks!
cy

**Comment by asmariyaz23** [comment]
Hello Cy!

Please find attached fastq file (subsetted first 100 reads). Please let me know if you see anything abnormal.
[trimmed.100reads.fastq.tar.gz](https://github.com/cytham/nanovar/files/4130296/trimmed.100reads.fastq.tar.gz)


Best,
Asma

**Comment by cytham** [comment]
Hi Asma,

Sorry for the late reply. 

NanoVar has been updated to v1.3.0. I have tested your reads on this new version and it ran successfully. Please reinstall this new version and try running your data again.

Sorry again for the delay and thanks for trying out NanoVar. Let me know how it goes.

Best,
cy

**Comment by asmariyaz23** [comment]
Hi Cytham,

Yes! this release seems to have solved the issues with those samples. Thank you for the new release.

Regards,
Asma
