### ISSUE TITLE
Error: Unrecognized CIGAR translated symbol "3"

### ISSUE THREAD

**Issue by infotmatician** [cytham/nanovar#41]
Dear developers,

Hope you are doing well. I am getting an error when I run the nanovar. I have already done with all dependencies and everything I hope, but I guess I have a problem with my .bam file the problem is
Error: Unrecognized CIGAR translated symbol "3" 
Is it related to my sample being Direct-Rna Seq?
I am using basic usage which you mentioned on the main page for the command

Best Regards

**Comment by cytham** [comment]
@infotmatician 

Thank you for reporting the issue.

The error refers to the "N" symbol in the CIGAR string which refers to "skipped region from the reference". I believe this might appear when spliced mRNA reads are mapped to the reference genome. 

Unfortunately, NanoVar currently do not support SV calling from RNA reads. We will consider having this feature in the future.

In the meantime, you may want to try to map the RNA reads to a transcriptome reference (No introns), which may leave out the "N"s in the CIGAR and might work with NanoVar.

Thanks

**Comment by infotmatician** [comment]
Thank you for the response  I wish you all a good day
