### ISSUE TITLE
Unable to install using conda

### ISSUE THREAD

**Issue by beantkapoor786** [cytham/nanovar#43]
Hello, I am unable to install the software using Conda. Here is the code that I am using - 
```
conda create -n nanovar
conda activate nanovar
conda install -c bioconda nanovar
```
It is stuck at this step for at least a couple hours - 
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
```
Any suggestion is greatly appreciated. Thank you.

**Comment by cytham** [comment]
Hi, can you try to specify the version of NanoVar?
```
conda install -c bioconda nanovar==1.4.1
```
Have you also make sure your channels are set correctly for bioconda? See below
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by beantkapoor786** [comment]
Hello, sorry for the late reply but I am still stuck on the same message `Solving environment: \` even when I used this code 
```
conda install -c bioconda nanovar=1.4.1
```
I think I have set my channels correctly for bioconda. Here are the contents of my `.condarc` file -
```
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: flexible
```
Please let me know if there is anything else I can try. Thank you.

**Comment by cytham** [comment]
I think this is a problem with the Conda repositories. 

Can you try
```
conda config --set channel_priority strict
```
if doesn't work, try
```
conda config --set channel_priority disable
```
or else, change it back to flexible
```
conda config --set channel_priority flexible
```
and try installing nanovar=1.4.1 again.

**Comment by beantkapoor786** [comment]
Using this code worked - 
```
conda config --set channel_priority disabled
```
It is now installed. Thank you for all your help.
