### ISSUE TITLE
HTML Report Figure's Aren't Showing

### ISSUE THREAD

**Issue by Mrromeros** [cytham/nanovar#49]
Hello, I used Nanovar on a test dataset of MinION data from SRA, and was able to produce the .pass.vcf and .total.vcf files without any issues, and the HTML report is generated but I cannot view any of the figures.

I have attached the image below of what my report looks like. I am not sure if this is just a problem with the HTML or the actual execution, seeing how the program executed without errors, I don't see why it wouldn't populate the graphs. 

For context, I am currently running NanoVar v1.4.1 through Conda (Python=3.8) on Ubuntu 20.04.

![NanoSV_problems](https://user-images.githubusercontent.com/68712667/185251838-76b39c80-8b26-4f7b-8595-85c1d8ce1829.PNG)

**Comment by cytham** [comment]
@Mrromeros The HTML should only be opened in the folder it was created as it is not a standalone file. Did you take it out of the original folder? Sorry for this inconvenience

**Comment by cytham** [comment]
The HTML file requires the `fig`, `css` and `js` folders, so please transfer them too and make sure they are in the same folder.

**Comment by Mrromeros** [comment]
That solved the problem! Thank you for the quick assistance!
