### ISSUE TITLE
Error loading vcf file into IGV

### ISSUE THREAD

**Issue by jagos01** [cytham/nanovar#5]
Hello Cytham,
I am trying to load .pass.nanovar.vcf into IGV.  I get the following error:

The provided VCF file is malformed at approximately line number 27: the END value in the INFO field is not valid.

The value in the INFO field for END is '.'  I believe it is expecting an integer.  Several other lines contain this value for END.  Can I change this value to any integer or is there another way to import the VCF file into IGV.  NanoVar v1.2.7 was used to generate the VCF files.
Thanks,
Scott

**Comment by benoukraflab** [comment]
Hi Scott,

Thanks for using NanoVar and I'm sorry for the IGV upload error.

I will be fixing this issue in the next version 1.2.8 that I'll be releasing in the next few days. I suggest you to wait for this version and re-run your sample.

Regards,
cy

**Comment by jagos01** [comment]
Thanks Cytham, I will re-rurn the data with the new version.  I have a
couple more questions.
1.   I compared the same data run on v1.0.2 and 1.2.7.  Significantly more
sv are called with v1.2.7.  Would this be due to the threshold dropping
from 2.6 to 1 or a change in the model?

2.  Does NanoVar still work with higher genome coverages (eg. 100x) or is
it better to have lower coverage (4-10x)?

Thanks,
Scott

**Comment by benoukraflab** [comment]
Hi Scott,

Sorry for the late reply.

1. Yes, it's due to both a threshold drop and a new model. The v1.2.7 detects more SVs at single read coverage but might also lead to increase false positives. I will be resolving this issue in the next version. 

2. NanoVar should still work with higher genome coverages. I have tested till 40X coverage and I believe it will work with even higher coverages.

Best,
cy

**Comment by cytham** [comment]
Hi Scott,

NanoVar has been updated to v1.3.0. I have fixed the VCF formatting and it is now able to be read into IGV. Please reinstall this new version and try it out.

Sorry for the delay in the update and thanks for trying out NanoVar. Let me know how it goes.

Best,
cy

**Comment by jagos01** [comment]
Hello Cytham,
I reinstalled NanoVar v1.3.0 (using conda).  When I run it I get the following error:
NanoVar started
Checking integrity of input files - -
Indexing genome and aligning reads - -
Analyzing read alignments and detecting SVs - \Traceback (most recent call last):
  File "/home/scott/miniconda3/envs/nanovarV1.3.0/bin/nanovar", line 452, in <module>
    main()
  File "/home/scott/miniconda3/envs/nanovarV1.3.0/bin/nanovar", line 264, in main
    from nanovar.nv_characterize import VariantDetect
  File "/home/scott/miniconda3/envs/nanovarV1.3.0/lib/python3.7/site-packages/nanovar/nv_characterize.py", line 26, in <module>
    from nanovar.nv_bam_parser import bam_parse
ModuleNotFoundError: No module named 'nanovar.nv_bam_parser'

Your help would be appreciated.  I have attached the log file.
[NanoVar-280220-1542.log](https://github.com/cytham/nanovar/files/4269449/NanoVar-280220-1542.log)

Thanks,
Scott

**Comment by benoukraflab** [comment]
Dear Scott,

My apologies for the error, I have overlooked the 'nv_bam_parser' compilation procedures. I have fixed the issue in v1.3.1.

Thanks for raising this problem.

Best,
cy

**Comment by jagos01** [comment]
Hello Cy,
I installed v1.3.1 and it ran without a problem.  However when loading  .pass.nanovar.vcf into IGV I get the following error:

Unable to parse header with error:  Your input file has a malformed header:  Unclosed quote in header line value equal to 1.0>, for input source: ......

There were two line with unclosed quotes in them 
##FILTER=<ID=PASS,Description="Quality above/equal to 1.0>
##FILTER=<ID=FAIL,Description="Quality below 1.0>
I closed the quotes and it loaded into IGV.  

Thank you for your help,
Scott

**Comment by cytham** [comment]
Hi Scott,

Thanks for raising the problem and identifying the specific malformed headers. I will rectify them in the next update. Strangely, my IGV did not raise that error, I guess that it might be a different version from yours.

Please continue to feedback about NanoVar's performance, I greatly appreciate your comments!

Best,
Cy
