### ISSUE TITLE
IndexError : list index out of range

### ISSUE THREAD

**Issue by skeremaydin** [cytham/nanovar#71]
nanovar -t 24 /truba/home/saaydin/nanopore_wgs/bamfiles/minimap/DRR258593.bam /truba/home/saaydin/nanopore_wgs/reference_genomes/Homo_sapiens_assembly38.fasta  /truba/home/saaydin/nanopore_wgs/nanovar/vcf_files/DRR258593/
I run this code but took this bug
![WhatsApp Image 2023-12-19 at 20 07 22](https://github.com/cytham/nanovar/assets/73022480/32c0f5ef-edac-457b-9bf8-8d9d1f4510a3)

**Comment by cytham** [comment]
Hi @skeremaydin, what is your NanoVar version? Can you please try with the latest version on GitHub?

```
git clone https://github.com/cytham/nanovar.git 
cd nanovar 
pip install .
```

**Comment by skeremaydin** [comment]
Thank you for replying. I checked my reference genome, it does not contain those symbols. 
If you install with pip, you can have version 1.5.0. Yet, when you install the package with mamba or conda from the bioconda, the 1.2.7 version is installed. When 1.5.0 version one is run, ModuleNotFoundError: No module named 'cytocad' error occurs, whereas in 1.2.7 version, the IndexError : list index out of range error persist.

**Comment by cytham** [comment]
Hi @skeremaydin, thanks for letting me know the bioconda issue, it might be due to dependency clashes. Did you install NanoVar on a freshly created conda environment?

Please install it through GitHub for now, the Pip version has a bug. 
Here's how to do it:
```
git clone https://github.com/cytham/nanovar.git 
cd nanovar 
pip install .
```

**Comment by skeremaydin** [comment]
Hello again. Yes, I did. I could install the 1.5.0 version of nanovar in a new created environment. Yet, this time I get this error 
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Thank you for your help. I am gonna try what I can do and find solution.

**Comment by cytham** [comment]
Did you try installing from github?

**Comment by skeremaydin** [comment]
Your instructions helped me solve my problem. Thank you very much!
