### ISSUE TITLE
Specifying specific regions to INCLUDE when variant calling (done adaptive sampling for nanopore sequencing)

### ISSUE THREAD

**Issue by nbertholdpgc** [cytham/nanovar#72]
Hi all. I have a question about the filtering process for targeting particular regions. I know you can supply a bed file to specify regions to EXCLUDE from variant calling. However, I have performed adaptive sampling for my nanopore sequencing and have 8 regions of 200kb in size. I suppose I could supply a bed file for the exclusion flag with everything except my 8 target regions, but I'm wondering if theres a more efficient way?

Cheers guys!!

**Comment by cytham** [comment]
Close due to inactivity
