### ISSUE TITLE
update conda version 

### ISSUE THREAD

**Issue by bwlang** [cytham/nanovar#76]
Thanks for sharing this interesting work!
I struggled a bit with the conda version, which seems to be broken.
Maybe you could update or remove it to avoid others getting stuck?

**Comment by cytham** [comment]
Hi @bwlang, there is an issue installing NanoVar with Conda now. Can you please install using pip inside your conda env?

`pip install nanovar`

We will try to resolve the conda issue soon, sorry for the inconvenience.

**Comment by bwlang** [comment]
I was able to get things working that way (and got some nice results - thanks!)
Maybe it's worth removing it from conda until you are able to resolve the issue.
