### ISSUE TITLE
How to use nanovar to do population-scale SV calling?

### ISSUE THREAD

**Issue by xiekunwhy** [cytham/nanovar#8]
Hi,

How to use nanovar to do population-scale SV calling when there a lot of samples (like Iceland populaiton https://www.biorxiv.org/content/10.1101/848366v1)?

Best wishes
Kun

**Comment by cytham** [comment]
Hi Kun,

NanoVar is a genomic SV caller. It detects SVs from long-read WGS data. For SV analysis on a population-scale, NanoVar is only involved in SV discovery where it detects SVs for individuals in the population, generating a VCF file for each individual. Any downstream analysis from the VCF files requires other tools and databases. I am currently developing a SV analysis tool which can annotate and compare SVs in a cohort. Hopefully it will be ready in the next month.

As for now, you can probably begin by aggregating the SVs from all the individual VCF files and discover hotspot clusters of SVs shared among most individuals.

Best,
cy

**Comment by xiekunwhy** [comment]
Hi cy,

Thank you for your reply, hope tools coming soon.

Best,
Kun
