### ISSUE TITLE
Alternative sequence in VCF

### ISSUE THREAD

**Issue by jiadong324** [cytham/nanovar#81]
Hi, 

Is that possible to add the alternative sequence in the VCF file?

**Comment by cytham** [comment]
Hi @jiadong324 , let me try to work on this.

**Comment by jiadong324** [comment]
@cytham Hey, I found you update to v1.6.2, just wondering whether it is able to report the alternative sequence in the VCF file. Thanks!

**Comment by cytham** [comment]
Hi @jiadong324, still working on this, will include the alternative sequences of INS and DEL SVs in the next update. I need a few more days. Thank you for your patience.

**Comment by cytham** [comment]
Hi @jiadong324, I have a beta version that I am still testing. If you would like to try it first, you can clone it from the branch by:

`git clone -b add-alt-seq https://github.com/cytham/nanovar.git`

Appreciate any feedback.

I will merge it into the master once I'm done testing in the next few days.

Thanks

**Comment by jiadong324** [comment]
Thanks for the update, I will wait once you merge to master.

**Comment by cytham** [comment]
Alt sequence versions have been merged into master. I'll close this for now.
