### ISSUE TITLE
Bam input  -  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 4: invalid start byte

### ISSUE THREAD

**Issue by Jyoti-Mridha** [cytham/nanovar#88]
Hi,
While using the nanovar with fastq files, it is running well. (nanovar /pfs/home/jyotimridha/Mito_ONT/Structural_variants/Batch1/fq_zip/barcode06.fastq.gz /pfs/home/jyotimridha/Mito_ONT/Database_Mito_Genome_hg38/nanovar/hg38_chrM.fa /pfs/home/jyotimridha/Mito_ONT/Structural_variants/Batch1/nanovar/barcode06/)

The same command when i am using for bam input i am encountering the following error.
**Mapping reads and calling SVs - /    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 4: invalid start byte**

Here i am copying the command which i have used
nanovar /pfs/home/jyotimridha/Mito_ONT/Batch1_3runs/previous_bam/barcode06_sorted.bam /pfs/home/jyotimridha/Mito_ONT/Database_Mito_Genome_hg38/nanovar/hg38_chrM.fa /pfs/home/jyotimridha/Mito_ONT/Structural_variants/Batch1/nanovar/barcode06_bam/

My bam is mapped with minimap2, then samtools view, sort and indexed.
Same bam file I am using for other "SV"  tools is working fine, but with nanovar i am not sure whether i am making a mistake in which part while running nanovar using the bam file.

Any help will be really appreciate, I value the insights and guidance.

**Comment by cytham** [comment]
Hi, thanks for report this. Can you attach the log file please, thanks

**Comment by Jyoti-Mridha** [comment]
Hellow,
 Please find here is attached log file.

**Comment by cytham** [comment]
@Jyoti-Mridha Can't view the log, nevermind, please try the latest version v1.7.0

**Comment by cytham** [comment]
Close due to inactivity
