### ISSUE TITLE
Nanovar makeblastdb failed

### ISSUE THREAD

**Issue by jiadong324** [cytham/nanovar#9]
Hi,

I installed nanovar through conda, and add makeblastdb, windowmasker and hs-blastn to the conda virtual environment. I am running on a server, here is the log file. 

[NanoVar-110320-1908.log](https://github.com/cytham/nanovar/files/4318989/NanoVar-110320-1908.log)

It seems that makeblastdb trying to modify some data, and it is not permitted.

Looking forward to your reply, thanks!

**Comment by cytham** [comment]
Hi,

I think you might not have write permissions for your reference genome directory ('genome'). makeblastdb needs to create genome indexes in the same directory of the input reference genome. 

You can do `ls -lh /home/DATA/REFGENOMEDB/human/GRCh38_full_analysis_set_plus_decoy_hla/genome`  to check if you have write permissions. Also, you can just try to make a file in that directory to test.

Best,
cy

**Comment by jiadong324** [comment]
@cytham Thanks, I see the reason.

**Comment by jiadong324** [comment]
@cytham 

Hi,

I got another issue, where the contig name contains some invalid symblos. The contig name is HLA-A*01:01:01:01.  

Btw, I am using the reference genome GRCh38_full_analysis_set_plus_decoy_hla.fa from 1000 Genome Projects.

**Comment by cytham** [comment]
The current version 1.3.2 does not support contigs with symbols "~, :, -" in their id. You need to remove these contigs from the reference genome, or wait for the next update coming soon.

Sorry for the inconvenience.

**Comment by cytham** [comment]
@jiadong324 NanoVar version >=1.3.3 now omits reference contigs with invalid symbols instead of producing an error.

**Comment by jiadong324** [comment]
@cytham Thanks for your kind reminder. I met another issue, running function run.cluster_nn().  I attach the error message below:


[minimap_nanovar_ONT240.txt](https://github.com/cytham/nanovar/files/4372604/minimap_nanovar_ONT240.txt)

**Comment by cytham** [comment]
@jiadong324 can you try to reinstall NanoVar using conda? `conda install nanovar —force-reinstall`

**Comment by jiadong324** [comment]
@cytham Thanks for your feedback!

**Comment by jiadong324** [comment]
@cytham 

Hi, 

I reinstall nanovar as you mentioned. I do have problem with load_model function, and it seems to be the issue from keras in tensorflow. Therefore, I also reinstall the tensorflow package under my conda environment. It dose not work as usual. 

I also tried a new conda environment for nanovar, which still dose not work.

Do you have any ideas of the issue?

Thanks!

**Comment by cytham** [comment]
@jiadong324 can you show me the error for the load_model?

**Comment by jiadong324** [comment]
Hi,

Here is the screenshot of the error. 

![error_screenshot](https://user-images.githubusercontent.com/6951612/78200391-1cdd5980-74c1-11ea-9e8f-68835c21356d.png)

The model under nanovar packages are:
ANN.E63B400L2N12-5D0.4-0.3SGDsee31_het_v1.h5
ANN.E63B400L2N12-5D0.4-0.3SGDsee31_het_v2.h5
ANN.E70B100L3N12-5D0.4-0.2SGDsee11_het_v5.h5

Thanks!

**Comment by cytham** [comment]
@jiadong324 what NanoVar version are you using? Please do `nanovar -v`. 
Can you please re-install the most updated version (v1.3.5)? Because your models are outdated. 

Please try the load_model again with the new models.

Please also do `pip freeze > packages.txt` and attach the packages.txt file. Thanks

**Comment by jiadong324** [comment]
Hi,

I've recreated the environment and the above issue is solved. But another error occurs at nv_cluster.py of the loadread_bp() function. 

Here is the screenshot of the error.

![error](https://user-images.githubusercontent.com/6951612/78465452-7dba9b00-7728-11ea-8819-5adb97e732b0.png)

**Comment by cytham** [comment]
@jiadong324 Great that you resolved the issue. This new error might be caused by a bug. I will try to fix it in the next update.

Meanwhile, if you are willing, can you try to edit the nv_cluster.py script? It should be at `/home/jdlin/.conda/envs/py36/lib/python3.6/site-packages/nanovar/nv_cluster.py`. Can you change `raise Exception("Error: Main SV class not found")` on line 307 to `raise KeyError("Error: Main SV class not found")` and then try to run again.

Thanks

**Comment by jiadong324** [comment]
@cytham Ok, I will change the source code and try again. Thanks!

**Comment by jiadong324** [comment]
@cytham Hi, I've changed the code and there are still errors, please check the log file below. Thanks! 

[minimap_nanovar_ONT240.txt](https://github.com/cytham/nanovar/files/4453663/minimap_nanovar_ONT240.txt)

**Comment by cytham** [comment]
@jiadong324 Thanks a lot for trying it out. Ok I think I will need to replicate the error on my side to fix the problem. Do you mind running NanoVar with --debug option and send me `subdata.tsv` , `parse1.tsv`, `genome.sizes` and the log file?

Thanks for your continual support!

**Comment by jiadong324** [comment]
@cytham Hi, I've tried what you recommend.

1. You raise an exception at line 87, so I add the code you suggested before line 87 instead of after line 87.

2. I run nanovar by adding --debug. The file subdata.tsv and parse1.tsv should under the output directory, but I did not find them. 

3. The log file looks fine to me. Please check below.

[NanoVar-110420-1109.log](https://github.com/cytham/nanovar/files/4465734/NanoVar-110420-1109.log)

**Comment by cytham** [comment]
@jiadong324 I think you might have got the source code module wrong. You might have added the code to nv_cluster.py but its actually suppose to go to line 87 of nv_characterize.py. Example shown below:
```
# line 86 of nv_characterize.py
    def cluster_extract:  # line 87 of nv_characterize.py
        writer(os.path.join(self.dir, 'subdata.tsv'), self.total_subdata, self.debug)  # Add this line
        writer(os.path.join(self.dir, 'detect.tsv'), self.detect_out, self.debug)   # Add this line
        writer(os.path.join(self.dir, 'parse1.tsv'), self.total_out, self.debug)   # Add this line
        logging.info("Clustering SV breakends")    # Original line 88
        cluster_out = sv_cluster(self.total_subdata, self.total_out, self.buff, self.maxovl, self.mincov, 
        self.contig, False)  # Original line 89
        logging.info("Filtering INS and INV SVs")  # Original line 90
        ...
```
Sorry for the confusion.

**Comment by jiadong324** [comment]
@cytham Hi, the three TSV files are too big. Can I send you through email?

**Comment by cytham** [comment]
@jiadong324 Hi, thanks for generating the files. Please try this email e0054302@u.nus.edu

**Comment by cytham** [comment]
@jiadong324 Thanks for the files and your patience. I have fixed the bugs and release a new version of NanoVar 1.3.6. Please try it out and let me know if its okay.

Thanks!

**Comment by jiadong324** [comment]
@cytham Thanks for solving the problem, it works now!

**Comment by cytham** [comment]
@jiadong324 That's great! Thanks for your help!

**Comment by jiadong324** [comment]
@cytham I found another issue which related to conda install. 

The one I run successfully was installed on conda version 4.7.12. But it dose not work on conda 4.8.3 (latest version). By using the conda latest version, I can install the nanovar 1.3.2 instead of 1.3.6. 

You can check it out if this really happens, otherwise, it might be problem of my machine.

**Comment by cytham** [comment]
Hi @jiadong324, my conda version is also 4.8.3 and I am able to install nanovar-v1.3.6. 

Here are some tips:
1) Did you try with the bioconda channel like this `conda install -c bioconda nanovar`?

2) Did you set your channels properly for your new conda version?
The order is important here.
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
Please refer to https://bioconda.github.io/user/install.html under section 2.

Good luck and let me know if they work for you. Thanks

**Comment by jiadong324** [comment]
@cytham I found another issue, where the program is sensitivity to file name. For example, I accidentally have 'fa' in BAM file. Then the program starts to check GZIP and thus raise error. Please fix or mentioned it somewhere in the program.

Thanks!

**Comment by cytham** [comment]
@jiadong324 Thanks for letting me know, I will take note and fix it in the next patch!

**Comment by jiadong324** [comment]
@cytham Hi, I found another error while running a cancer cell line sequenced by PacBio CLR.

[Nanovar_SKBR3.txt](https://github.com/cytham/nanovar/files/4626257/Nanovar_SKBR3.txt)

**Comment by cytham** [comment]
@jiadong324 Thanks for reporting the error.
It seems like the blast output contains "0.0" as part of the coordinates, can you send me the "blast.tab" file for me to investigate?

Thanks

**Comment by jiadong324** [comment]
@cytham I found this file is big, I can share with you through OneDrive, is that ok for you?

**Comment by cytham** [comment]
@jiadong324 Sure, e0054302@u.nus.edu this is my email

**Comment by jiadong324** [comment]
@cytham I've send you a link, please check.

**Comment by cytham** [comment]
@jiadong324 the file you sent me is corrupted at the end. Perhaps something went wrong during the BLAST alignment step. I suggest that you rerun your sample with the new version I just released (v.1.37) and let me know how it goes.

Thanks!

**Comment by jiadong324** [comment]
@cytham Ok, I will try the new version. Before your update, I also found another issue. I will check if this happens for the latest version. 

BTW, do you need the shared file? If you don't, I will delete that file.

![image](https://user-images.githubusercontent.com/6951612/82850754-2965b780-9f30-11ea-845f-f259f71526ab.png)

**Comment by cytham** [comment]
@jiadong324 I don't need the shared file anymore, you can delete it, thanks.

That error might have been fixed in the new version, please try and let me know, thanks!
